//****CREATING TABLE*****//
CREATE TABLE EMPLOYEE(
EMPLOYEE_ID INT PRIMARY KEY,
EMPLOYEE_FIRST_NAME VARCHAR(10) NOT NULL,
EMPLOYEE_LAST_NAME VARCHAR(10),
EMPLOYEE_ADDRESS VARCHAR(50),
EMPLOYEE_SALARY INT
);

CREATE TABLE Employee(
Employee_ID INT PRIMARY KEY,
Employee_FIRST_NAME VARCHAR(20),
Employee_LAST_NAME VARCHAR(20),
Employee_ADDRESS VARCHAR(50),
Employee_SALARY INT,
Dep_ID INT,
KEY fk_employee_IDX(`Dep_ID`),
CONSTRAINT fk_employee_IDX FOREIGN KEY(`Dep_ID`) REFERENCES `Department`(`Department_ID`) ON DELETE CASCADE ON UPDATE CASCADE
);

INSERT INTO `department` VALUES(1,'HR');
INSERT INTO `department` VALUES(2,'IT');
INSERT INTO `department` VALUES(3,'Finance');
INSERT INTO `department` VALUES(4,'Networking');
INSERT INTO `department` VALUES(5,'CCD');

//***************************************************** JOINS ***************************************************************************//

SELECT `employee`.`Employee_ID`,`employee`.`Employee_FIRST_NAME`,
`employee`.`Employee_LAST_NAME`,`employee`.`Employee_ADDRESS`,
`employee`.`Employee_SALARY`,`employee`.`Dep_ID`,
`department`.`Department_ID`,`department`.`Department_Name`
FROM `employee`,`department`
WHERE `employee`.`Dep_ID`=`department`.`Department_ID`;

/*****************************************************************INNER JOIN****************************************************************/

SELECT * FROM employee e
INNER JOIN `department` d
ON
e.`Dep_ID`=d.`Department_ID`;

/*****************************************************************LEFT OUTER JOIN****************************************************************/

SELECT * FROM employee e
LEFT OUTER JOIN `department` d
ON
e.`Dep_ID`=d.`Department_ID`;

/*****************************************************************RIGHT OUTER JOIN****************************************************************/

SELECT * FROM employee e
RIGHT OUTER JOIN `department` d
ON
e.`Dep_ID`=d.`Department_ID`;

/*****************************************************************FULL OUTER JOIN****************************************************************/

SELECT * FROM `employee` e
LEFT OUTER JOIN 
`department` d
ON
e.`Dep_ID`=d.`Department_ID`

UNION 

SELECT * FROM `employee` e
RIGHT OUTER JOIN 
`department` d
ON
 e.`Dep_ID`=d.`Department_ID`

/**********************************************************EMPLOYEE THAT DOES NOT BELONG TO ANY DEPARTMENT****************************************/

SELECT * FROM `employee` e
LEFT OUTER JOIN
`department` d
ON
e.`Dep_ID`=d.`Department_ID`
WHERE 
e.`Dep_ID` IS NULL;   


//**** INSERTING INTO TABLE *****//
INSERT INTO `EMPLOYEE` VALUES(522601,'PRAVIN','RAO','DOWNTOWN BANGLORE',250000); 
INSERT INTO `EMPLOYEE` VALUES(522602,'RAJIV','BANSAL','HYDERABAD SEZ',20000);
INSERT INTO `EMPLOYEE` VALUES(522603,'RAVI','VENKATESH','CHENNAI STP',150000);
INSERT INTO `EMPLOYEE` VALUES(522604,'DAVID','KENNEDY','ATLANTA SEZ',350000);
INSERT INTO `EMPLOYEE` VALUES(522605,'SHRIKANT','MOORTHY','BANGLORE HEADQUATERS',50000);
INSERT INTO `EMPLOYEE` VALUES(522606,'SANJAY','PUROHIT','INDORE SEZ',55000);
INSERT INTO `EMPLOYEE` VALUES(522607,'ROHIT','JADHAV','BANGLORE HEADQUATERS',200000);
INSERT INTO `EMPLOYEE` VALUES(522608,'KIRS','RAO','MYSORE GEC',100000);
INSERT INTO `EMPLOYEE` VALUES(522609,'AJIT','KULKARNI','MYSORE DC',25000);
INSERT INTO `EMPLOYEE` VALUES(522610,'MOHIT','JADHAV','MANGLORE DC',70000);

SELECT * FROM EMPLOYEE;
//**** FIRST MAXIMUM SALARY *****//
SELECT MAX(`EMPLOYEE_SALARY`) FROM EMPLOYEE;

//**** SECOND MAX SALARY ****//
SELECT MAX(`EMPLOYEE_SALARY`) FROM EMPLOYEE WHERE `EMPLOYEE_SALARY` NOT IN (SELECT MAX(`EMPLOYEE_SALARY`) FROM EMPLOYEE);

//**** THIRD MAX SALARY *****//
SELECT MAX(`EMPLOYEE_SALARY`) FROM EMPLOYEE WHERE `EMPLOYEE_SALARY` 
NOT IN (SELECT MAX(`EMPLOYEE_SALARY`) FROM EMPLOYEE WHERE `EMPLOYEE_SALARY` 
NOT IN (SELECT MAX(`EMPLOYEE_SALARY`) FROM EMPLOYEE));


//**** OTHER METHOD ****//
SELECT `EMPLOYEE_SALARY` FROM EMPLOYEE ORDER BY `EMPLOYEE_SALARY` DESC LIMIT 2,1;
SELECT `EMPLOYEE_SALARY` FROM EMPLOYEE ORDER BY `EMPLOYEE_SALARY` DESC LIMIT 1,1;
SELECT `EMPLOYEE_SALARY` FROM EMPLOYEE ORDER BY `EMPLOYEE_SALARY` DESC LIMIT 1;
SELECT `EMPLOYEE_SALARY` FROM EMPLOYEE ORDER BY `EMPLOYEE_SALARY` DESC LIMIT 3,1;


/** FIRST HIGHEST SALARY
SELECT * FROM `employee` ORDER BY `EMPLOYEE_SALARY` DESC LIMIT 0,1;

/** SECOND HIGHEST SALARY
SELECT * FROM `employee` ORDER BY `EMPLOYEE_SALARY` DESC LIMIT 2,1;

/**THIRD HIGHEST SALARY
SELECT * FROM `employee` ORDER BY `EMPLOYEE_SALARY` DESC LIMIT 3,1;

/** FOURTH HIGHEST SALARY
SELECT * FROM `employee` ORDER BY `EMPLOYEE_SALARY` DESC LIMIT 4,1;

/** FIFTH HIGHEST SALARY
SELECT * FROM `employee` ORDER BY `EMPLOYEE_SALARY` DESC LIMIT 5,1;



/** FIRST LOWEST SALARY
SELECT * FROM `employee` ORDER BY `EMPLOYEE_SALARY` LIMIT 1,1;

/** SECOND LOWEST SALARY
SELECT * FROM `employee` ORDER BY `EMPLOYEE_SALARY` LIMIT 2,1;

/**THIRD LOWEST SALARY
SELECT * FROM `employee` ORDER BY `EMPLOYEE_SALARY` LIMIT 3,1;

/** FOURTH LOWEST SALARY
SELECT * FROM `employee` ORDER BY `EMPLOYEE_SALARY` LIMIT 4,1;

/** FIFTH LOWEST SALARY
SELECT * FROM `employee` ORDER BY `EMPLOYEE_SALARY` LIMIT 5,1;



/**EMPLOYEE SALARY BETWEEN 20000 TO 50000
SELECT * FROM `employee` WHERE `EMPLOYEE_SALARY` BETWEEN 20000 AND 50000;(BOTH ENDS POINTS IS INCLUSIVE)

/**EMPLOYEE SALARY IS EITHER 20000 OR 50000
SELECT * FROM `employee` WHERE `EMPLOYEE_SALARY` IN (20000,50000);

/**EMPLOYEE SALARY IS NOT BETWEEN 20000 TO 50000
SELECT * FROM `employee` WHERE `EMPLOYEE_SALARY` NOT BETWEEN 20000 AND 50000;(BOTH ENDS POINTS IS EXCLUSIVE)




//***** MINIMUM SALARY *******//

SELECT MIN(`EMPLOYEE_SALARY`) FROM `EMPLOYEE`; 


SELECT MIN(`EMPLOYEE_SALARY`) FROM `EMPLOYEE`
WHERE `EMPLOYEE_SALARY` NOT IN (SELECT MIN(`EMPLOYEE_SALARY`) FROM `EMPLOYEE`) ;

SELECT MIN(`EMPLOYEE_SALARY`) FROM `EMPLOYEE`
WHERE `EMPLOYEE_SALARY` NOT IN (SELECT MIN(`EMPLOYEE_SALARY`) FROM `EMPLOYEE` 
WHERE `EMPLOYEE_SALARY` NOT IN (SELECT MIN(`EMPLOYEE_SALARY`) FROM `EMPLOYEE`));



//**** LIKE OPERATOR ****//
SELECT * FROM `employee` WHERE `Employee_FIRST_NAME` LIKE 'R_%_V';//FIRST NAME START WITH R AND ENDS WITH V
SELECT * FROM `EMPLOYEE` WHERE `EMPLOYEE_FIRST_NAME` NOT LIKE 's%';//FIRST NAME BEGINING WITH S 
SELECT * FROM `EMPLOYEE` WHERE `EMPLOYEE_FIRST_NAME` LIKE 'RA_%';//FRIST NAME BEGINING WITH RA
SELECT * FROM `EMPLOYEE` WHERE `EMPLOYEE_FIRST_NAME` LIKE '%_T';//FIRST NAME ENDING WITH T
SELECT * FROM `EMPLOYEE` WHERE `EMPLOYEE_LAST_NAME` LIKE '%O';//LAST NAME ENDING  WITH O
SELECT * FROM `EMPLOYEE` WHERE `EMPLOYEE_LAST_NAME` LIKE 'R%';//LAST NAME BEGINING WITH R
SELECT * FROM `EMPLOYEE` WHERE `EMPLOYEE_LAST_NAME` LIKE 'R_%';
SELECT * FROM `EMPLOYEE` WHERE `EMPLOYEE_LAST_NAME` LIKE '%_R_%';

SELECT `EMPLOYEE_FIRST_NAME`,COUNT(*) FROM `employee` GROUP BY `EMPLOYEE_FIRST_NAME`;

SELECT * FROM `employee` GROUP BY `EMPLOYEE_FIRST_NAME`;
SELECT `EMPLOYEE_FIRST_NAME`,`EMPLOYEE_LAST_NAME` FROM `employee` WHERE `EMPLOYEE_FIRST_NAME` LIKE 'S%' ORDER BY `EMPLOYEE_LAST_NAME` DESC;
SELECT * FROM `employee` GROUP BY `EMPLOYEE_FIRST_NAME`;
SELECT `EMPLOYEE_LAST_NAME`,COUNT(*) FROM `employee` GROUP BY `EMPLOYEE_LAST_NAME`;
SELECT MAX(`EMPLOYEE_ID`) FROM `employee`;

