 /*Table structure for table `st_faculty` */

DROP TABLE IF EXISTS `st_faculty`;

CREATE TABLE `st_faculty`(
`ID` BIGINT(20) NOT NULL AUTO_INCREMENT,
`COLLEGE_ID` BIGINT(20) DEFAULT NULL,
`COURSE_ID`  BIGINT(20) DEFAULT NULL,
`FIRST_NAME` VARCHAR(255) DEFAULT NULL,
`LAST_NAME` VARCHAR(255) DEFAULT NULL,
`QUALIFICATION` VARCHAR(255) DEFAULT NULL,
`DATE_OF_BIRTH` DATETIME DEFAULT NULL,
`MOBILE_NO` VARCHAR(255) DEFAULT NULL,
`EMAIL` VARCHAR(255) DEFAULT NULL,
`ADDRESS` VARCHAR(255) DEFAULT NULL,
`CREATED_BY` VARCHAR(255) DEFAULT NULL,
`MODIFIED_BY` VARCHAR(255) DEFAULT NULL,
`CREATED_DATETIME` DATETIME DEFAULT NULL,
`MODIFIED_DATETIME` DATETIME DEFAULT NULL,
PRIMARY KEY  (`ID`),
KEY `fk_st_faculty` (`COLLEGE_ID`),
KEY `fk_st_faculty2` (`COURSE_ID`),
 
CONSTRAINT `fk_st_faculty` FOREIGN KEY (`COLLEGE_ID`) REFERENCES `st_college` (`ID`) ON DELETE CASCADE ON UPDATE CASCADE ,
CONSTRAINT `fk_st_faculty2`  FOREIGN KEY  (`COURSE_ID`) REFERENCES  `st_course`  (`ID`) ON DELETE CASCADE ON UPDATE CASCADE
 
) ENGINE=INNODB DEFAULT CHARSET=latin1;