CREATE DATABASE JDBC_PROJECT;

CREATE TABLE MARKSHEET(
ROLL_NO VARCHAR(20) PRIMARY KEY,
FIRST_NAME VARCHAR(20),
CHEMISTRY INT,
PHYSICS INT,
MATHS INT 
);
SELECT * FROM MARKSHEET;

SELECT ROLL_NO,FIRST_NAME,PHYSICS,CHEMISTRY,MATHS,(PHYSICS+CHEMISTRY+MATHS) 
AS TOTAL_SCORE FROM MARKSHEET 
ORDER BY (PHYSICS+CHEMISTRY+MATHS) DESC;